@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue May 16 17:30:53 +0200 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto e6d0622e05b84e9fb5fb2b7fef4028fd --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_LedDriver_behav xil_defaultlib.tb_LedDriver -log elaborate.log"
call xelab  -wto e6d0622e05b84e9fb5fb2b7fef4028fd --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_LedDriver_behav xil_defaultlib.tb_LedDriver -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
