# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hicha/OneDrive/Bureau/TP05/Domaine_Horloge/Domaine_Horloge.srcs/sources_1/ip/PLL_Clock/PLL_Clock.xci
# IP: The module: 'PLL_Clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hicha/OneDrive/Bureau/TP05/Domaine_Horloge/Domaine_Horloge.gen/sources_1/ip/PLL_Clock/PLL_Clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_Clock'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hicha/OneDrive/Bureau/TP05/Domaine_Horloge/Domaine_Horloge.gen/sources_1/ip/PLL_Clock/PLL_Clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hicha/OneDrive/Bureau/TP05/Domaine_Horloge/Domaine_Horloge.gen/sources_1/ip/PLL_Clock/PLL_Clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/hicha/OneDrive/Bureau/TP05/Domaine_Horloge/Domaine_Horloge.srcs/sources_1/ip/PLL_Clock/PLL_Clock.xci
# IP: The module: 'PLL_Clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hicha/OneDrive/Bureau/TP05/Domaine_Horloge/Domaine_Horloge.gen/sources_1/ip/PLL_Clock/PLL_Clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hicha/OneDrive/Bureau/TP05/Domaine_Horloge/Domaine_Horloge.gen/sources_1/ip/PLL_Clock/PLL_Clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hicha/OneDrive/Bureau/TP05/Domaine_Horloge/Domaine_Horloge.gen/sources_1/ip/PLL_Clock/PLL_Clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_Clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
